require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PoststhreadsController do

  # This should return the minimal set of attributes required to create a valid
  # Poststhread. As you add validations to Poststhread, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all poststhreads as @poststhreads" do
      poststhread = Poststhread.create! valid_attributes
      get :index
      assigns(:poststhreads).should eq([poststhread])
    end
  end

  describe "GET show" do
    it "assigns the requested poststhread as @poststhread" do
      poststhread = Poststhread.create! valid_attributes
      get :show, :id => poststhread.id.to_s
      assigns(:poststhread).should eq(poststhread)
    end
  end

  describe "GET new" do
    it "assigns a new poststhread as @poststhread" do
      get :new
      assigns(:poststhread).should be_a_new(Poststhread)
    end
  end

  describe "GET edit" do
    it "assigns the requested poststhread as @poststhread" do
      poststhread = Poststhread.create! valid_attributes
      get :edit, :id => poststhread.id.to_s
      assigns(:poststhread).should eq(poststhread)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Poststhread" do
        expect {
          post :create, :poststhread => valid_attributes
        }.to change(Poststhread, :count).by(1)
      end

      it "assigns a newly created poststhread as @poststhread" do
        post :create, :poststhread => valid_attributes
        assigns(:poststhread).should be_a(Poststhread)
        assigns(:poststhread).should be_persisted
      end

      it "redirects to the created poststhread" do
        post :create, :poststhread => valid_attributes
        response.should redirect_to(Poststhread.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved poststhread as @poststhread" do
        # Trigger the behavior that occurs when invalid params are submitted
        Poststhread.any_instance.stub(:save).and_return(false)
        post :create, :poststhread => {}
        assigns(:poststhread).should be_a_new(Poststhread)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Poststhread.any_instance.stub(:save).and_return(false)
        post :create, :poststhread => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested poststhread" do
        poststhread = Poststhread.create! valid_attributes
        # Assuming there are no other poststhreads in the database, this
        # specifies that the Poststhread created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Poststhread.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => poststhread.id, :poststhread => {'these' => 'params'}
      end

      it "assigns the requested poststhread as @poststhread" do
        poststhread = Poststhread.create! valid_attributes
        put :update, :id => poststhread.id, :poststhread => valid_attributes
        assigns(:poststhread).should eq(poststhread)
      end

      it "redirects to the poststhread" do
        poststhread = Poststhread.create! valid_attributes
        put :update, :id => poststhread.id, :poststhread => valid_attributes
        response.should redirect_to(poststhread)
      end
    end

    describe "with invalid params" do
      it "assigns the poststhread as @poststhread" do
        poststhread = Poststhread.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Poststhread.any_instance.stub(:save).and_return(false)
        put :update, :id => poststhread.id.to_s, :poststhread => {}
        assigns(:poststhread).should eq(poststhread)
      end

      it "re-renders the 'edit' template" do
        poststhread = Poststhread.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Poststhread.any_instance.stub(:save).and_return(false)
        put :update, :id => poststhread.id.to_s, :poststhread => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested poststhread" do
      poststhread = Poststhread.create! valid_attributes
      expect {
        delete :destroy, :id => poststhread.id.to_s
      }.to change(Poststhread, :count).by(-1)
    end

    it "redirects to the poststhreads list" do
      poststhread = Poststhread.create! valid_attributes
      delete :destroy, :id => poststhread.id.to_s
      response.should redirect_to(poststhreads_url)
    end
  end

end
